'use strict';
const N=256,D=256,T=Math.PI*2,P=(Math.sqrt(5)-1)/2,$=x=>document.getElementById(x);
function rng(s){return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296}}
function env(seed){const r=rng(seed),a=new Float64Array(N*D);for(let i=0;i<a.length;i++)a[i]=(r()-.5)*2e-3;return a}
function perturb(seed){const r=rng(seed),a=new Float64Array(N*D);for(let b=0;b<N;b++)for(let j=0;j<D;j++){const p=T*j*P;a[b*D+j]=Math.sin(p*(1+b%7)+seed%11)+.41*Math.cos(p*(1+b%5))+(r()-.5)*.02}return a}
function add(a,b){const o=new Float64Array(a.length);for(let i=0;i<a.length;i++)o[i]=a[i]+b[i];return o}
function dilute(a,w){const o=new Float64Array(a.length);for(let i=0;i<a.length;i++)o[i]=.1*a[i]+.9*w[i];return o}
function see(a,f,n,seed){const r=rng(seed),o=new Float64Array(a.length);for(let i=0;i<a.length;i++){let v=a[i]+(r()-.5)*2*n;o[i]=Math.abs(v)<f?0:v}return o}
function scramble(a,seed){const r=rng(seed),o=a.slice();for(let b=0;b<N;b++)for(let j=D-1;j>0;j--){const k=(r()*(j+1))|0,i=b*D+j,q=b*D+k;[o[i],o[q]]=[o[q],o[i]]}return o}
function sig(a){const o=new Float64Array(N*3);for(let b=0;b<N;b++){let pr=0,pi=0,nr=0,ni=0,zr=0,zi=0,s=0;for(let j=0;j<D;j++){const v=a[b*D+j],m=Math.abs(v),ph=T*j*P,c=Math.cos(ph),q=Math.sin(ph);s+=m;if(v>0){pr+=m*c;pi+=m*q}else if(v<0){nr+=m*c;ni+=m*q}else{zr+=c;zi+=q}}const z=b*3;o[z]=s?Math.hypot(pr,pi)/s:0;o[z+1]=s?Math.hypot(nr,ni)/s:0;o[z+2]=Math.hypot(zr,zi)/D}return o}
function dist(a,b){let s=0;for(let i=0;i<a.length;i++){const d=a[i]-b[i];s+=d*d}return Math.sqrt(s/a.length)}
function run(){const R=+$('rounds').value,F=10**(-+$('floor').value),Q=10**(-+$('noise').value),W=env(17);let A=add(W,perturb(101)),B=add(W,perturb(211)),C=W.slice(),S=A.slice(),rows=[],depth=0;for(let k=0;k<=R;k++){const a=sig(see(A,F,Q,1000+k)),b=sig(see(B,F,Q,2000+k)),c=sig(see(C,F,Q,3000+k)),s=sig(see(S,F,Q,4000+k));const ab=dist(a,b),an=(dist(a,c)+dist(b,c))/2,as=dist(a,s);if(an>Math.max(F,Q)*3)depth=k;rows.push({k,ab,an,as,mat:10**(-k)});if(k<R){A=dilute(A,W);B=dilute(B,W);C=dilute(C,W);S=scramble(dilute(S,W),7000+k)}}const z=rows.at(-1);$('material').textContent=z.mat<F?'below perception':z.mat.toExponential(1);$('lineage').textContent=z.ab.toExponential(2);$('nullsep').textContent=z.an.toExponential(2);$('depth').textContent=depth+' / '+R;draw(rows)}
function draw(rows){const c=$('chart'),g=c.getContext('2d'),W=c.width,H=c.height,p=48;g.clearRect(0,0,W,H);g.font='13px system-ui';g.fillStyle='#8d98a3';g.strokeStyle='#293038';for(let i=0;i<5;i++){let y=p+i*(H-2*p)/4;g.beginPath();g.moveTo(p,y);g.lineTo(W-p,y);g.stroke();g.fillText(String(-i*3),10,y+4)}[['ab',[]],['an',[10,6]],['as',[3,6]]].forEach(([key,dash],ix)=>{g.setLineDash(dash);g.strokeStyle=['#eef2f5','#a4afb9','#68737d'][ix];g.beginPath();rows.forEach((r,i)=>{const v=Math.log10(Math.max(1e-12,r[key])),x=p+i*(W-2*p)/(rows.length-1),y=p+(0-Math.max(-12,Math.min(0,v)))*(H-2*p)/12;i?g.lineTo(x,y):g.moveTo(x,y)});g.stroke()});g.setLineDash([]);g.fillStyle='#c8d0d7';g.fillText('solid S₁↔S₂   dashed lineage↔null   dotted S₁↔scramble',p,H-15)}
['rounds','floor','noise'].forEach(id=>$(id).addEventListener('input',()=>{$('roundsOut').textContent=$('rounds').value;$('floorOut').textContent='1e-'+$('floor').value;$('noiseOut').textContent='1e-'+$('noise').value}));$('run').addEventListener('click',run);run();